<?php
$amfuncs = array(
	'内容管理'=> array(
		'normal' => '文档内容',
		'commu' => '交互内容',
		'static' => '静态管理',
		'farchive' => '副件内容',
	),
	'会员管理'=> array(
		'member' => '普通会员管理',
		'amember' => '管理员管理',
		'utrans' => '会员组变更',
		'save' => '积分充/扣值',
		'pay' => '现金充值管理',
		'trusteeship' => '会员中心代管',
	),
	'其它管理'=> array(
		'fragment' => '碎片管理',
		'gather' => '采集管理',
		'database' => '数据库相关',
		'sitemap' => 'SiteMap地图',
		'record' => '站点日志',
		'smsapi' => '短信接口管理',
		'weixin' => '微信接口管理',
		'other' => '其它权限',
	),
	'模板与架构'=> array(
		'tpl' => '模板风格',
		'channel' => '文档模型',
		'catalog' => '类目管理',
		'cfcommu' => '扩展架构',
		'currency' => '积分设置',
		'mchannel' => '会员架构',
		'freeinfo' => '副件架构',
		'pusharea' => '推送架构',
	),
	'系统设置'=> array(
		'webparam' => '网站参数',
		'bkconfig' => '管理后台配置',
		'mcconfig' => '会员中心配置',
		'project' => '方案管理',
		'affix' => '附属设置',
		'bannedip' => '禁止IP',
	),
);