<?php
$sysparams = array (
  'suffix' => 'pub|cn\\.com|com|net|org|cn|hk|cc|cm|tv|mobi|info|biz|travel|asia|me|tel|name|co|so|ca|de|com\\.cn|net\\.cn|org\\.cn|gov\\.cn|ac\\.cn',
  'nouser' =>
  array (
    'mid' => '0',
    'mname' => '游客',
    'password' => '',
    'email' => '',
    'clicks' => '0',
    'archives' => '0',
    'comments' => '0',
  ),
  /**
   *  定义自动加载前缀与路径，如果一个前缀绑定多个地址则用逗号分隔，路径分隔符可用 “.” 区分，也可直接用 “/”
   *  （注：不包含双引号）；默认地址如果指定了完整路径则以指定的路径加载，如：D:/www/web 则把前缀注册到该路径下，
   *  如果不指定，如格式为：include 则以网站根目录算起，即该前缀会注册到地址为  M_ROOT . 'include' 里。
   */
  'autoload' =>
  array (
    '_08_M_' => array(
                    _08_EXTEND_APPLICATION_PATH.'models|1',
                    _08_APPLICATION_PATH.'models|1',
                    _08_EXTEND_DIR.'.'._08_LIBS_DIR.'.classes|1',
                    _08_ADMIN . '.models|1',
                    _08_LIBS_DIR.'.classes|1'
                ),
    '_08_C_' => array(
                    _08_APPLICATION_PATH.'controllers|1',
                    _08_INCLUDE_DIR.'.application',
                    _08_ADMIN_PATH . '.controllers',
                    _08_LIBS_DIR.'.classes|1'
                ),
    '_08' =>    array(
                    _08_INCLUDE_DIR,
                    _08_ADMIN . '.controllers|1',
                    _08_ADMIN . '.models|1',
                    _08_INCLUDE_DIR.'.application',
                    _08_LIBS_DIR.'.classes|1'
                ),
    'cls_' =>   array(
                    _08_INCLUDE_DIR,
                    _08_ADMIN,
                    _08_EXTEND_DIR.'.'._08_LIBS_DIR.'.classes|1',
                    _08_ADMIN . '.controllers|1',
                    _08_ADMIN . '.models|1',
                    _08_INCLUDE_DIR.'.application',
                    _08_LIBS_DIR.'.classes|1'
                ),
    'cac_' =>   array(
                    //_08_CACHE_DIR.'.'._08_USERCACHE_DIR,
                    _08_EXTEND_DIR.'.'._08_CACHE_DIR.'.'._08_SYSCACHE_DIR,
                    _08_CACHE_DIR.'.'._08_SYSCACHE_DIR                    
                )
  ),

  'keepwords' =>
  array (
    0 => 'add',
    1 => 'all',
    2 => 'alter',
    3 => 'analyze',
    4 => 'and',
    5 => 'as',
    6 => 'asc',
    7 => 'asensitive',
    8 => 'before',
    9 => 'between',
    10 => 'bigint',
    11 => 'binary',
    12 => 'blob',
    13 => 'both',
    14 => 'by',
    15 => 'call',
    16 => 'cascade',
    17 => 'case',
    18 => 'change',
    19 => 'char',
    20 => 'character',
    21 => 'check',
    22 => 'collate',
    23 => 'column',
    24 => 'condition',
    25 => 'connection',
    26 => 'constraint',
    27 => 'continue',
    28 => 'convert',
    29 => 'create',
    30 => 'cross',
    31 => 'current_date',
    32 => 'current_time',
    33 => 'current_timestamp',
    34 => 'current_user',
    35 => 'cursor',
    36 => 'database',
    37 => 'databases',
    38 => 'day_hour',
    39 => 'day_microsecond',
    40 => 'day_minute',
    41 => 'day_second',
    42 => 'dec',
    43 => 'decimal',
    44 => 'declare',
    45 => 'default',
    46 => 'delayed',
    47 => 'delete',
    48 => 'desc',
    49 => 'describe',
    50 => 'deterministic',
    51 => 'distinct',
    52 => 'distinctrow',
    53 => 'div',
    54 => 'double',
    55 => 'drop',
    56 => 'dual',
    57 => 'each',
    58 => 'else',
    59 => 'elseif',
    60 => 'enclosed',
    61 => 'escaped',
    62 => 'exists',
    63 => 'exit',
    64 => 'explain',
    65 => 'false',
    66 => 'fetch',
    67 => 'float',
    68 => 'float4',
    69 => 'float8',
    70 => 'for',
    71 => 'force',
    72 => 'foreign',
    73 => 'from',
    74 => 'fulltext',
    75 => 'goto',
    76 => 'grant',
    77 => 'group',
    78 => 'having',
    79 => 'high_priority',
    80 => 'hour_microsecond',
    81 => 'hour_minute',
    82 => 'hour_second',
    83 => 'if',
    84 => 'ignore',
    85 => 'in',
    86 => 'index',
    87 => 'infile',
    88 => 'inner',
    89 => 'inout',
    90 => 'insensitive',
    91 => 'insert',
    92 => 'int',
    93 => 'int1',
    94 => 'int2',
    95 => 'int3',
    96 => 'int4',
    97 => 'int8',
    98 => 'integer',
    99 => 'interval',
    100 => 'into',
    101 => 'is',
    102 => 'iterate',
    103 => 'join',
    104 => 'key',
    105 => 'keys',
    106 => 'kill',
    107 => 'label',
    108 => 'leading',
    109 => 'leave',
    110 => 'left',
    111 => 'like',
    112 => 'limit',
    113 => 'linear',
    114 => 'lines',
    115 => 'load',
    116 => 'localtime',
    117 => 'localtimestamp',
    118 => 'lock',
    119 => 'long',
    120 => 'longblob',
    121 => 'longtext',
    122 => 'loop',
    123 => 'low_priority',
    124 => 'match',
    125 => 'mediumblob',
    126 => 'mediumint',
    127 => 'mediumtext',
    128 => 'middleint',
    129 => 'minute_microsecond',
    130 => 'minute_second',
    131 => 'mod',
    132 => 'modifies',
    133 => 'natural',
    134 => 'not',
    135 => 'no_write_to_binlog',
    136 => 'null',
    137 => 'numeric',
    138 => 'on',
    139 => 'optimize',
    140 => 'option',
    141 => 'optionally',
    142 => 'or',
    143 => 'order',
    144 => 'out',
    145 => 'outer',
    146 => 'outfile',
    147 => 'precision',
    148 => 'primary',
    149 => 'procedure',
    150 => 'purge',
    151 => 'raid0',
    152 => 'range',
    153 => 'read',
    154 => 'reads',
    155 => 'real',
    156 => 'references',
    157 => 'regexp',
    158 => 'release',
    159 => 'rename',
    160 => 'repeat',
    161 => 'replace',
    162 => 'require',
    163 => 'restrict',
    164 => 'return',
    165 => 'revoke',
    166 => 'right',
    167 => 'rlike',
    168 => 'schema',
    169 => 'schemas',
    170 => 'second_microsecond',
    171 => 'select',
    172 => 'sensitive',
    173 => 'separator',
    174 => 'set',
    175 => 'show',
    176 => 'smallint',
    177 => 'spatial',
    178 => 'specific',
    179 => 'sql',
    180 => 'sqlexception',
    181 => 'sqlstate',
    182 => 'sqlwarning',
    183 => 'sql_big_result',
    184 => 'sql_calc_found_rows',
    185 => 'sql_small_result',
    186 => 'ssl',
    187 => 'starting',
    188 => 'straight_join',
    189 => 'table',
    190 => 'terminated',
    191 => 'then',
    192 => 'tinyblob',
    193 => 'tinyint',
    194 => 'tinytext',
    195 => 'to',
    196 => 'trailing',
    197 => 'trigger',
    198 => 'true',
    199 => 'undo',
    200 => 'union',
    201 => 'unique',
    202 => 'unlock',
    203 => 'unsigned',
    204 => 'update',
    205 => 'usage',
    206 => 'use',
    207 => 'using',
    208 => 'utc_date',
    209 => 'utc_time',
    210 => 'utc_timestamp',
    211 => 'values',
    212 => 'varbinary',
    213 => 'varchar',
    214 => 'varcharacter',
    215 => 'varying',
    216 => 'when',
    217 => 'where',
    218 => 'while',
    219 => 'with',
    220 => 'write',
    221 => 'x509',
    222 => 'xor',
    223 => 'year_month',
    224 => 'zerofill',
    225 => 'action',
    226 => 'bit',
    227 => 'date',
    228 => 'enum',
    229 => 'no',
    230 => 'text',
    231 => 'text',
    232 => 'time',
    233 => 'timestamp',
  ),
) ;