<?php
defined('M_COM') || exit('No Permission');
$_pafieldspush_98 = array (
  'subject' => 
  array (
    'ename' => 'subject',
    'datatype' => 'text',
    'type' => 'pa',
    'tpid' => 'push_98',
    'cname' => '标题',
    'issystem' => '1',
    'iscustom' => '0',
    'iscommon' => '1',
    'issearch' => '0',
    'available' => '1',
    'tbl' => 'push_98',
    'length' => '100',
    'vieworder' => '0',
    'rpid' => '0',
    'wmid' => '0',
    'guide' => '',
    'vdefault' => '',
    'innertext' => '',
    'fromcode' => '0',
    'nohtml' => '1',
    'notnull' => '1',
    'mlimit' => '',
    'regular' => '',
    'min' => '',
    'max' => '',
    'mode' => '1',
    'coid' => '0',
    'cnmode' => '0',
    'cfgs' => 
    array (
    ),
    'cfgs0' => '',
    'filter' => '0',
    'editor_height' => '0',
  ),
  'url' => 
  array (
    'ename' => 'url',
    'datatype' => 'text',
    'type' => 'pa',
    'tpid' => 'push_98',
    'cname' => 'URL',
    'issystem' => '0',
    'iscustom' => '0',
    'iscommon' => '1',
    'issearch' => '0',
    'available' => '1',
    'tbl' => 'push_98',
    'length' => '255',
    'vieworder' => '0',
    'rpid' => '0',
    'wmid' => '0',
    'guide' => '',
    'vdefault' => '',
    'innertext' => '',
    'fromcode' => '0',
    'nohtml' => '1',
    'notnull' => '1',
    'mlimit' => '',
    'regular' => '',
    'min' => '',
    'max' => '',
    'mode' => '1',
    'coid' => '0',
    'cnmode' => '0',
    'cfgs' => 
    array (
    ),
    'cfgs0' => '',
    'filter' => '0',
    'editor_height' => '0',
  ),
  'thumb' => 
  array (
    'ename' => 'thumb',
    'datatype' => 'image',
    'type' => 'pa',
    'tpid' => 'push_98',
    'cname' => '缩略图',
    'issystem' => '0',
    'iscustom' => '0',
    'iscommon' => '1',
    'issearch' => '0',
    'available' => '1',
    'tbl' => 'push_98',
    'length' => '0',
    'vieworder' => '0',
    'rpid' => '0',
    'wmid' => '0',
    'guide' => '',
    'vdefault' => '',
    'innertext' => '',
    'fromcode' => '0',
    'nohtml' => '1',
    'notnull' => '0',
    'mlimit' => '',
    'regular' => '',
    'min' => '',
    'max' => '',
    'mode' => '0',
    'coid' => '0',
    'cnmode' => '0',
    'cfgs' => 
    array (
    ),
    'cfgs0' => '',
    'filter' => '0',
    'editor_height' => '0',
  ),
  'classid1' => 
  array (
    'ename' => 'classid1',
    'datatype' => 'cacc',
    'type' => 'pa',
    'tpid' => 'push_98',
    'cname' => '栏目',
    'issystem' => '0',
    'iscustom' => '0',
    'iscommon' => '1',
    'issearch' => '0',
    'available' => '1',
    'tbl' => 'push_98',
    'length' => '0',
    'vieworder' => '0',
    'rpid' => '0',
    'wmid' => '0',
    'guide' => '',
    'vdefault' => '',
    'innertext' => 'return ex_get_msuns(\'516\',0,1);',
    'fromcode' => '0',
    'nohtml' => '0',
    'notnull' => '0',
    'mlimit' => '',
    'regular' => '',
    'min' => '',
    'max' => '',
    'mode' => '0',
    'coid' => '0',
    'cnmode' => '0',
    'cfgs' => 
    array (
    ),
    'cfgs0' => '',
    'filter' => '0',
    'editor_height' => '0',
  ),
  'classid2' => 
  array (
    'ename' => 'classid2',
    'datatype' => 'cacc',
    'type' => 'pa',
    'tpid' => 'push_98',
    'cname' => '问题状态',
    'issystem' => '0',
    'iscustom' => '0',
    'iscommon' => '1',
    'issearch' => '0',
    'available' => '1',
    'tbl' => 'push_98',
    'length' => '0',
    'vieworder' => '0',
    'rpid' => '0',
    'wmid' => '0',
    'guide' => '',
    'vdefault' => '',
    'innertext' => '',
    'fromcode' => '0',
    'nohtml' => '0',
    'notnull' => '0',
    'mlimit' => '',
    'regular' => '',
    'min' => '',
    'max' => '',
    'mode' => '0',
    'coid' => '35',
    'cnmode' => '0',
    'cfgs' => 
    array (
    ),
    'cfgs0' => '',
    'filter' => '0',
    'editor_height' => '0',
  ),
) ;