<?php
defined('M_COM') || exit('No Permission');
$fcatalogs = array (
  'fcatalog180' => 
  array (
    'fcaid' => 'fcatalog180',
    'title' => '直播',
    'pid' => '',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog181' => 
  array (
    'fcaid' => 'fcatalog181',
    'title' => '直播内容页958_176',
    'pid' => 'fcatalog180',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog118' => 
  array (
    'fcaid' => 'fcatalog118',
    'title' => '整站首页',
    'pid' => '',
    'vieworder' => 3,
    'chid' => '1',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog119' => 
  array (
    'fcaid' => 'fcatalog119',
    'title' => '导航上ad_788_70',
    'pid' => 'fcatalog118',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '暂不用',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog175' => 
  array (
    'fcaid' => 'fcatalog175',
    'title' => '幻灯片下300_125',
    'pid' => 'fcatalog118',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '团购没内容时调用',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog176' => 
  array (
    'fcaid' => 'fcatalog176',
    'title' => '幻灯片下300_270',
    'pid' => 'fcatalog118',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '看房团没内容时调用',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog157' => 
  array (
    'fcaid' => 'fcatalog157',
    'title' => '大小图1000_300_70',
    'pid' => 'fcatalog118',
    'vieworder' => 1,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog120' => 
  array (
    'fcaid' => 'fcatalog120',
    'title' => '导航下ad_1000_70',
    'pid' => 'fcatalog118',
    'vieworder' => 2,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '暂不用',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog121' => 
  array (
    'fcaid' => 'fcatalog121',
    'title' => '搜索左ad_160_120',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog122' => 
  array (
    'fcaid' => 'fcatalog122',
    'title' => '搜索右ad_160_120',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog123' => 
  array (
    'fcaid' => 'fcatalog123',
    'title' => '搜索下文字1',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '1',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '暂不用',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog124' => 
  array (
    'fcaid' => 'fcatalog124',
    'title' => '搜索下文字2',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '1',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '暂不用',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog125' => 
  array (
    'fcaid' => 'fcatalog125',
    'title' => '搜索下文字3',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '1',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog126' => 
  array (
    'fcaid' => 'fcatalog126',
    'title' => '搜索下文字4',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '1',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog127' => 
  array (
    'fcaid' => 'fcatalog127',
    'title' => '搜索下ad_620_80',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog128' => 
  array (
    'fcaid' => 'fcatalog128',
    'title' => '搜索下ad_1000_70',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog129' => 
  array (
    'fcaid' => 'fcatalog129',
    'title' => '幻灯片',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog133' => 
  array (
    'fcaid' => 'fcatalog133',
    'title' => '新房上ad_1000_70',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog134' => 
  array (
    'fcaid' => 'fcatalog134',
    'title' => '家装上ad_1000_70',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog135' => 
  array (
    'fcaid' => 'fcatalog135',
    'title' => '置业上ad_1000_70',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog165' => 
  array (
    'fcaid' => 'fcatalog165',
    'title' => '对联广告100_300',
    'pid' => 'fcatalog118',
    'vieworder' => 3,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog16' => 
  array (
    'fcaid' => 'fcatalog16',
    'title' => '图片友情',
    'pid' => 'fcatalog118',
    'vieworder' => 4,
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog17' => 
  array (
    'fcaid' => 'fcatalog17',
    'title' => '文字友情',
    'pid' => 'fcatalog118',
    'vieworder' => 4,
    'chid' => '1',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog154' => 
  array (
    'fcaid' => 'fcatalog154',
    'title' => '地区分站',
    'pid' => '',
    'vieworder' => 10,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog155' => 
  array (
    'fcaid' => 'fcatalog155',
    'title' => '大小图1000_300_70',
    'pid' => 'fcatalog154',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => 'farea:{ccid1}',
    'checked' => '1',
    'farea' => '1',
  ),
  'fcatalog164' => 
  array (
    'fcaid' => 'fcatalog164',
    'title' => '搜索下1000_70',
    'pid' => 'fcatalog154',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => 'farea:{ccid1}',
    'checked' => '1',
    'farea' => '1',
  ),
  'fcatalog163' => 
  array (
    'fcaid' => 'fcatalog163',
    'title' => '头条下380_30',
    'pid' => 'fcatalog154',
    'vieworder' => '1',
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => 'farea:{ccid1}',
    'checked' => '1',
    'farea' => '1',
  ),
  'fcatalog159' => 
  array (
    'fcaid' => 'fcatalog159',
    'title' => '地区首页幻灯片4',
    'pid' => 'fcatalog154',
    'vieworder' => '2',
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => 'farea:{ccid1}',
    'checked' => '1',
    'farea' => '1',
  ),
  'fcatalog160' => 
  array (
    'fcaid' => 'fcatalog160',
    'title' => '新房上ad_1000_70',
    'pid' => 'fcatalog154',
    'vieworder' => '2',
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => 'farea:{ccid1}',
    'checked' => '1',
    'farea' => '1',
  ),
  'fcatalog161' => 
  array (
    'fcaid' => 'fcatalog161',
    'title' => '家装上ad_1000_70',
    'pid' => 'fcatalog154',
    'vieworder' => '2',
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => 'farea:{ccid1}',
    'checked' => '1',
    'farea' => '1',
  ),
  'fcatalog162' => 
  array (
    'fcaid' => 'fcatalog162',
    'title' => '置业上ad_1000_70',
    'pid' => 'fcatalog154',
    'vieworder' => '2',
    'chid' => '2',
    'autocheck' => '0',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => 'farea:{ccid1}',
    'checked' => '1',
    'farea' => '1',
  ),
  'fcatalog2' => 
  array (
    'fcaid' => 'fcatalog2',
    'title' => '新房频道',
    'pid' => '',
    'vieworder' => 20,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog141' => 
  array (
    'fcaid' => 'fcatalog141',
    'title' => '幻灯片290_231',
    'pid' => 'fcatalog2',
    'vieworder' => 0,
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog24' => 
  array (
    'fcaid' => 'fcatalog24',
    'title' => '检索下1000_70(3)',
    'pid' => 'fcatalog2',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog3' => 
  array (
    'fcaid' => 'fcatalog3',
    'title' => '二手频道',
    'pid' => '',
    'vieworder' => 30,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog156' => 
  array (
    'fcaid' => 'fcatalog156',
    'title' => '感兴趣下740_65',
    'pid' => 'fcatalog3',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog30' => 
  array (
    'fcaid' => 'fcatalog30',
    'title' => '导航下1000_70(3)',
    'pid' => 'fcatalog3',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog4' => 
  array (
    'fcaid' => 'fcatalog4',
    'title' => '出租频道',
    'pid' => '',
    'vieworder' => 40,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog167' => 
  array (
    'fcaid' => 'fcatalog167',
    'title' => '感兴趣下740_65',
    'pid' => 'fcatalog4',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog31' => 
  array (
    'fcaid' => 'fcatalog31',
    'title' => '导航下1000_70(3)',
    'pid' => 'fcatalog4',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog113' => 
  array (
    'fcaid' => 'fcatalog113',
    'title' => '资讯频道',
    'pid' => '',
    'vieworder' => 50,
    'chid' => '2',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog114' => 
  array (
    'fcaid' => 'fcatalog114',
    'title' => '导航上ad_1000_70',
    'pid' => 'fcatalog113',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog115' => 
  array (
    'fcaid' => 'fcatalog115',
    'title' => '视频上ad_1000_70',
    'pid' => 'fcatalog113',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog116' => 
  array (
    'fcaid' => 'fcatalog116',
    'title' => '新房上ad_1000_70',
    'pid' => 'fcatalog113',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog23' => 
  array (
    'fcaid' => 'fcatalog23',
    'title' => '内容页280(4)',
    'pid' => 'fcatalog113',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog22' => 
  array (
    'fcaid' => 'fcatalog22',
    'title' => '二手资讯270_250',
    'pid' => 'fcatalog113',
    'vieworder' => 1,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog117' => 
  array (
    'fcaid' => 'fcatalog117',
    'title' => '家装资讯270_250',
    'pid' => 'fcatalog113',
    'vieworder' => 2,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog169' => 
  array (
    'fcaid' => 'fcatalog169',
    'title' => '专题频道',
    'pid' => '',
    'vieworder' => 50,
    'chid' => '2',
    'autocheck' => '0',
    'apmid' => '0',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog170' => 
  array (
    'fcaid' => 'fcatalog170',
    'title' => '导航上1000_70',
    'pid' => 'fcatalog169',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog171' => 
  array (
    'fcaid' => 'fcatalog171',
    'title' => '专题右侧280_300',
    'pid' => 'fcatalog169',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog143' => 
  array (
    'fcaid' => 'fcatalog143',
    'title' => '家装频道',
    'pid' => '',
    'vieworder' => 60,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog104' => 
  array (
    'fcaid' => 'fcatalog104',
    'title' => '导航下左文字',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '1',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog106' => 
  array (
    'fcaid' => 'fcatalog106',
    'title' => '检索右207_168',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog109' => 
  array (
    'fcaid' => 'fcatalog109',
    'title' => '装修公司207_172',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog112' => 
  array (
    'fcaid' => 'fcatalog112',
    'title' => '量房banner1000_314',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog144' => 
  array (
    'fcaid' => 'fcatalog144',
    'title' => 'logo右790_70',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog146' => 
  array (
    'fcaid' => 'fcatalog146',
    'title' => '搜索上1000_70',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog147' => 
  array (
    'fcaid' => 'fcatalog147',
    'title' => '设计师下743_100',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog102' => 
  array (
    'fcaid' => 'fcatalog102',
    'title' => '导航下1000_70',
    'pid' => 'fcatalog143',
    'vieworder' => '1',
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog145' => 
  array (
    'fcaid' => 'fcatalog145',
    'title' => '导航下左368_245',
    'pid' => 'fcatalog143',
    'vieworder' => '1',
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog32' => 
  array (
    'fcaid' => 'fcatalog32',
    'title' => '视频频道',
    'pid' => '',
    'vieworder' => 70,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog33' => 
  array (
    'fcaid' => 'fcatalog33',
    'title' => '首页导航下1000_70',
    'pid' => 'fcatalog32',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog34' => 
  array (
    'fcaid' => 'fcatalog34',
    'title' => '内容页280(4)',
    'pid' => 'fcatalog32',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog136' => 
  array (
    'fcaid' => 'fcatalog136',
    'title' => '问答频道',
    'pid' => '',
    'vieworder' => 90,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog137' => 
  array (
    'fcaid' => 'fcatalog137',
    'title' => '导航上1000_70',
    'pid' => 'fcatalog136',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog138' => 
  array (
    'fcaid' => 'fcatalog138',
    'title' => '首页右198_213',
    'pid' => 'fcatalog136',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog139' => 
  array (
    'fcaid' => 'fcatalog139',
    'title' => '首页右198_150',
    'pid' => 'fcatalog136',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog166' => 
  array (
    'fcaid' => 'fcatalog166',
    'title' => '专家团720_120',
    'pid' => 'fcatalog136',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog178' => 
  array (
    'fcaid' => 'fcatalog178',
    'title' => '图库频道',
    'pid' => '',
    'vieworder' => 91,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '0',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog179' => 
  array (
    'fcaid' => 'fcatalog179',
    'title' => '顶部1000_70',
    'pid' => 'fcatalog178',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog172' => 
  array (
    'fcaid' => 'fcatalog172',
    'title' => '手机版界面',
    'pid' => '',
    'vieworder' => 100,
    'chid' => '2',
    'autocheck' => '0',
    'apmid' => '0',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog173' => 
  array (
    'fcaid' => 'fcatalog173',
    'title' => '手机客户端',
    'pid' => 'fcatalog172',
    'vieworder' => 0,
    'chid' => '35',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog174' => 
  array (
    'fcaid' => 'fcatalog174',
    'title' => '手机版',
    'pid' => 'fcatalog172',
    'vieworder' => 0,
    'chid' => '36',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog177' => 
  array (
    'fcaid' => 'fcatalog177',
    'title' => '手机下载图标',
    'pid' => 'fcatalog172',
    'vieworder' => 0,
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog28' => 
  array (
    'fcaid' => 'fcatalog28',
    'title' => '辅助信息',
    'pid' => '',
    'vieworder' => 110,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog168' => 
  array (
    'fcaid' => 'fcatalog168',
    'title' => '帮助中心-广告联系',
    'pid' => 'fcatalog28',
    'vieworder' => 0,
    'chid' => '34',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
  ),
  'fcatalog26' => 
  array (
    'fcaid' => 'fcatalog26',
    'title' => '网站信息',
    'pid' => 'fcatalog28',
    'vieworder' => 0,
    'chid' => '4',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
  ),
  'fcatalog29' => 
  array (
    'fcaid' => 'fcatalog29',
    'title' => '帮助信息',
    'pid' => 'fcatalog28',
    'vieworder' => 0,
    'chid' => '5',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
  ),
) ;