<?php
defined('M_COM') || exit('No Permission');
$_ffields2 = array (
  'flash' => 
  array (
    'ename' => 'flash',
    'datatype' => 'flash',
    'type' => 'f',
    'tpid' => '2',
    'cname' => 'FLASH',
    'issystem' => '0',
    'iscustom' => '1',
    'iscommon' => '0',
    'issearch' => '0',
    'available' => '1',
    'tbl' => 'farchives_2',
    'length' => '0',
    'vieworder' => 0,
    'rpid' => '0',
    'wmid' => '0',
    'guide' => '',
    'vdefault' => '',
    'innertext' => '',
    'fromcode' => '0',
    'nohtml' => '0',
    'notnull' => '0',
    'mlimit' => '',
    'regular' => '',
    'min' => '',
    'max' => '',
    'mode' => '0',
    'coid' => '0',
    'cnmode' => '0',
    'cfgs' => 
    array (
    ),
    'cfgs0' => '',
    'filter' => '0',
    'editor_height' => '0',
  ),
  'html' => 
  array (
    'ename' => 'html',
    'datatype' => 'multitext',
    'type' => 'f',
    'tpid' => '2',
    'cname' => 'HTML',
    'issystem' => '0',
    'iscustom' => '1',
    'iscommon' => '0',
    'issearch' => '0',
    'available' => '1',
    'tbl' => 'farchives_2',
    'length' => '0',
    'vieworder' => 0,
    'rpid' => '0',
    'wmid' => '0',
    'guide' => '',
    'vdefault' => '',
    'innertext' => '',
    'fromcode' => '0',
    'nohtml' => '0',
    'notnull' => '0',
    'mlimit' => '',
    'regular' => '',
    'min' => '',
    'max' => '',
    'mode' => '1',
    'coid' => '0',
    'cnmode' => '0',
    'cfgs' => 
    array (
    ),
    'cfgs0' => '',
    'filter' => '0',
    'editor_height' => '0',
  ),
  'image' => 
  array (
    'ename' => 'image',
    'datatype' => 'image',
    'type' => 'f',
    'tpid' => '2',
    'cname' => '图片',
    'issystem' => '0',
    'iscustom' => '1',
    'iscommon' => '0',
    'issearch' => '0',
    'available' => '1',
    'tbl' => 'farchives_2',
    'length' => '0',
    'vieworder' => 0,
    'rpid' => '0',
    'wmid' => '0',
    'guide' => '',
    'vdefault' => '',
    'innertext' => '',
    'fromcode' => '0',
    'nohtml' => '0',
    'notnull' => '0',
    'mlimit' => '',
    'regular' => '',
    'min' => '',
    'max' => '',
    'mode' => '0',
    'coid' => '0',
    'cnmode' => '0',
    'cfgs' => 
    array (
    ),
    'cfgs0' => '',
    'filter' => '0',
    'editor_height' => '0',
  ),
  'link' => 
  array (
    'cname' => '链接',
    'ename' => 'link',
    'datatype' => 'text',
    'type' => 'f',
    'tpid' => '2',
    'issystem' => '0',
    'iscustom' => '1',
    'iscommon' => '0',
    'tbl' => 'farchives_2',
    'guide' => '',
    'cfgs' => '',
    'vieworder' => 0,
    'available' => '1',
    'length' => '255',
    'min' => '',
    'max' => '',
    'vdefault' => '',
    'issearch' => '0',
    'rpid' => '0',
    'wmid' => '0',
    'innertext' => '',
    'fromcode' => '0',
    'nohtml' => '1',
    'notnull' => '0',
    'mlimit' => '',
    'regular' => '',
    'mode' => '1',
    'coid' => '0',
    'cnmode' => '0',
    'filter' => '0',
    'editor_height' => '0',
  ),
  'subject' => 
  array (
    'ename' => 'subject',
    'datatype' => 'text',
    'type' => 'f',
    'tpid' => '2',
    'cname' => '标题',
    'issystem' => '1',
    'iscustom' => '0',
    'iscommon' => '1',
    'issearch' => '0',
    'available' => '1',
    'tbl' => 'farchives',
    'length' => '255',
    'vieworder' => 0,
    'rpid' => '0',
    'wmid' => '0',
    'guide' => '',
    'vdefault' => '',
    'innertext' => '',
    'fromcode' => '0',
    'nohtml' => '0',
    'notnull' => '1',
    'mlimit' => '0',
    'regular' => '',
    'min' => '',
    'max' => '',
    'mode' => '0',
    'coid' => '0',
    'cnmode' => '0',
    'cfgs' => 
    array (
    ),
    'cfgs0' => '',
    'filter' => '0',
    'editor_height' => '0',
  ),
) ;