<?php
defined('M_COM') || exit('No Permission');
$_ffields34 = array (
  'subject' => 
  array (
    'ename' => 'subject',
    'datatype' => 'text',
    'type' => 'f',
    'tpid' => '34',
    'cname' => '标题',
    'issystem' => '1',
    'iscustom' => '0',
    'iscommon' => '1',
    'issearch' => '0',
    'available' => '1',
    'tbl' => 'farchives',
    'length' => '255',
    'vieworder' => '0',
    'rpid' => '0',
    'wmid' => '0',
    'guide' => '',
    'vdefault' => '',
    'innertext' => '',
    'fromcode' => '0',
    'nohtml' => '0',
    'notnull' => '1',
    'mlimit' => '0',
    'regular' => '',
    'min' => '',
    'max' => '',
    'mode' => '0',
    'coid' => '0',
    'cnmode' => '0',
    'cfgs' => 
    array (
    ),
    'cfgs0' => '',
    'filter' => '0',
    'editor_height' => '0',
  ),
  'lxfs' => 
  array (
    'ename' => 'lxfs',
    'datatype' => 'texts',
    'type' => 'f',
    'tpid' => '34',
    'cname' => '文本集信息',
    'issystem' => '0',
    'iscustom' => '1',
    'iscommon' => '0',
    'issearch' => '0',
    'available' => '1',
    'tbl' => 'farchives_34',
    'length' => '0',
    'vieworder' => '0',
    'rpid' => '0',
    'wmid' => '0',
    'guide' => '目前限制3条，若要加，请在副件模型[文本集信息]设置',
    'vdefault' => '',
    'innertext' => '电话名称|0|20
电话号码|0|20',
    'fromcode' => '0',
    'nohtml' => '0',
    'notnull' => '0',
    'mlimit' => '',
    'regular' => '',
    'min' => '0',
    'max' => '3',
    'mode' => '0',
    'coid' => '0',
    'cnmode' => '0',
    'cfgs' => 
    array (
    ),
    'cfgs0' => '',
    'filter' => '0',
    'editor_height' => '0',
  ),
) ;