<?php
defined('M_COM') || exit('No Permission');
$fcatalogs = array (
  'fcatalog118' => 
  array (
    'fcaid' => 'fcatalog118',
    'title' => '整站首页',
    'pid' => '',
    'vieworder' => 3,
    'chid' => '1',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog119' => 
  array (
    'fcaid' => 'fcatalog119',
    'title' => '顶部1200_60',
    'pid' => 'fcatalog118',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog175' => 
  array (
    'fcaid' => 'fcatalog175',
    'title' => '幻灯片右270_140',
    'pid' => 'fcatalog118',
    'vieworder' => 5,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog120' => 
  array (
    'fcaid' => 'fcatalog120',
    'title' => '精选专题上1200_60',
    'pid' => 'fcatalog118',
    'vieworder' => 10,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog128' => 
  array (
    'fcaid' => 'fcatalog128',
    'title' => '特惠楼盘上1200_60',
    'pid' => 'fcatalog118',
    'vieworder' => 15,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog176' => 
  array (
    'fcaid' => 'fcatalog176',
    'title' => '特惠楼盘右270_148',
    'pid' => 'fcatalog118',
    'vieworder' => 18,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog133' => 
  array (
    'fcaid' => 'fcatalog133',
    'title' => '新盘推荐上1200_60',
    'pid' => 'fcatalog118',
    'vieworder' => 20,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog134' => 
  array (
    'fcaid' => 'fcatalog134',
    'title' => '商业地产上1200_60',
    'pid' => 'fcatalog118',
    'vieworder' => 25,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog127' => 
  array (
    'fcaid' => 'fcatalog127',
    'title' => '商业地产左270_190',
    'pid' => 'fcatalog118',
    'vieworder' => 30,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog135' => 
  array (
    'fcaid' => 'fcatalog135',
    'title' => '商业地产右270_125',
    'pid' => 'fcatalog118',
    'vieworder' => 32,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog165' => 
  array (
    'fcaid' => 'fcatalog165',
    'title' => '二手房上1200_60',
    'pid' => 'fcatalog118',
    'vieworder' => 35,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog17' => 
  array (
    'fcaid' => 'fcatalog17',
    'title' => '文字友情',
    'pid' => 'fcatalog118',
    'vieworder' => 50,
    'chid' => '1',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog154' => 
  array (
    'fcaid' => 'fcatalog154',
    'title' => '地区分站',
    'pid' => '',
    'vieworder' => 10,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog155' => 
  array (
    'fcaid' => 'fcatalog155',
    'title' => '大小图1200_300_70',
    'pid' => 'fcatalog154',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => 'farea:{ccid1}',
    'checked' => '1',
    'farea' => '1',
  ),
  'fcatalog164' => 
  array (
    'fcaid' => 'fcatalog164',
    'title' => '搜索下1200_70',
    'pid' => 'fcatalog154',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => 'farea:{ccid1}',
    'checked' => '1',
    'farea' => '1',
  ),
  'fcatalog159' => 
  array (
    'fcaid' => 'fcatalog159',
    'title' => '地区首页幻灯片4',
    'pid' => 'fcatalog154',
    'vieworder' => 2,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => 'farea:{ccid1}',
    'checked' => '1',
    'farea' => '1',
  ),
  'fcatalog160' => 
  array (
    'fcaid' => 'fcatalog160',
    'title' => '新房上ad_1200_70',
    'pid' => 'fcatalog154',
    'vieworder' => 2,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => 'farea:{ccid1}',
    'checked' => '1',
    'farea' => '1',
  ),
  'fcatalog162' => 
  array (
    'fcaid' => 'fcatalog162',
    'title' => '置业上ad_1200_70',
    'pid' => 'fcatalog154',
    'vieworder' => 2,
    'chid' => '2',
    'autocheck' => '0',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => 'farea:{ccid1}',
    'checked' => '1',
    'farea' => '1',
  ),
  'fcatalog2' => 
  array (
    'fcaid' => 'fcatalog2',
    'title' => '新房频道',
    'pid' => '',
    'vieworder' => 20,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog08' => 
  array (
    'fcaid' => 'fcatalog08',
    'title' => '团购列表广告1200_70',
    'pid' => 'fcatalog2',
    'vieworder' => 0,
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => 0,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalogxf' => 
  array (
    'fcaid' => 'fcatalogxf',
    'title' => '新房导航下广告位',
    'pid' => 'fcatalog2',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog4' => 
  array (
    'fcaid' => 'fcatalog4',
    'title' => '二手出租',
    'pid' => '',
    'vieworder' => 40,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog31' => 
  array (
    'fcaid' => 'fcatalog31',
    'title' => '二手出租导航下广告位',
    'pid' => 'fcatalog4',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog113' => 
  array (
    'fcaid' => 'fcatalog113',
    'title' => '资讯频道',
    'pid' => '',
    'vieworder' => 50,
    'chid' => '2',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog1111' => 
  array (
    'fcaid' => 'fcatalog1111',
    'title' => '资讯列表上ad_1200_60',
    'pid' => 'fcatalog113',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 0,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalognews' => 
  array (
    'fcaid' => 'fcatalognews',
    'title' => '资讯导航下广告位',
    'pid' => 'fcatalog113',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog169' => 
  array (
    'fcaid' => 'fcatalog169',
    'title' => '专题频道',
    'pid' => '',
    'vieworder' => 50,
    'chid' => '2',
    'autocheck' => '0',
    'apmid' => '0',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog171' => 
  array (
    'fcaid' => 'fcatalog171',
    'title' => '专题右侧280_300',
    'pid' => 'fcatalog169',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalogspecial' => 
  array (
    'fcaid' => 'fcatalogspecial',
    'title' => '专题导航下广告位',
    'pid' => 'fcatalog169',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalogbusiness' => 
  array (
    'fcaid' => 'fcatalogbusiness',
    'title' => '商业地产频道',
    'pid' => '',
    'vieworder' => 50,
    'chid' => '2',
    'autocheck' => '0',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'farea' => '0',
    'params' => '',
    'checked' => '0',
  ),
  'fcatalogsydc' => 
  array (
    'fcaid' => 'fcatalogsydc',
    'title' => '商业地产导航下广告位',
    'pid' => 'fcatalogbusiness',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalogmoney' => 
  array (
    'fcaid' => 'fcatalogmoney',
    'title' => '赚佣金频道',
    'pid' => '',
    'vieworder' => 50,
    'chid' => '2',
    'autocheck' => '0',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'farea' => '0',
    'params' => '',
    'checked' => '0',
  ),
  'fcatalogzyj' => 
  array (
    'fcaid' => 'fcatalogzyj',
    'title' => '赚佣金导航下广告位',
    'pid' => 'fcatalogmoney',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog143' => 
  array (
    'fcaid' => 'fcatalog143',
    'title' => '家装频道',
    'pid' => '',
    'vieworder' => 60,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog104' => 
  array (
    'fcaid' => 'fcatalog104',
    'title' => '导航下左文字',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '1',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog106' => 
  array (
    'fcaid' => 'fcatalog106',
    'title' => '检索右207_168',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog109' => 
  array (
    'fcaid' => 'fcatalog109',
    'title' => '装修公司207_172',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog112' => 
  array (
    'fcaid' => 'fcatalog112',
    'title' => '量房banner1000_314',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog144' => 
  array (
    'fcaid' => 'fcatalog144',
    'title' => 'logo右790_70',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog146' => 
  array (
    'fcaid' => 'fcatalog146',
    'title' => '搜索上1000_70',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog147' => 
  array (
    'fcaid' => 'fcatalog147',
    'title' => '设计师下743_100',
    'pid' => 'fcatalog143',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog102' => 
  array (
    'fcaid' => 'fcatalog102',
    'title' => '导航下1000_70',
    'pid' => 'fcatalog143',
    'vieworder' => '1',
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog145' => 
  array (
    'fcaid' => 'fcatalog145',
    'title' => '导航下左368_245',
    'pid' => 'fcatalog143',
    'vieworder' => '1',
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog180' => 
  array (
    'fcaid' => 'fcatalog180',
    'title' => '直播',
    'pid' => '',
    'vieworder' => 60,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog181' => 
  array (
    'fcaid' => 'fcatalog181',
    'title' => '直播内容页958_176',
    'pid' => 'fcatalog180',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog32' => 
  array (
    'fcaid' => 'fcatalog32',
    'title' => '视频频道',
    'pid' => '',
    'vieworder' => 70,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog35' => 
  array (
    'fcaid' => 'fcatalog35',
    'title' => '首页导航下1200_60',
    'pid' => 'fcatalog32',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog136' => 
  array (
    'fcaid' => 'fcatalog136',
    'title' => '问答频道',
    'pid' => '',
    'vieworder' => 90,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog137' => 
  array (
    'fcaid' => 'fcatalog137',
    'title' => '问答导航下广告位',
    'pid' => 'fcatalog136',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog138' => 
  array (
    'fcaid' => 'fcatalog138',
    'title' => '首页右238_195',
    'pid' => 'fcatalog136',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog139' => 
  array (
    'fcaid' => 'fcatalog139',
    'title' => '首页右238_150',
    'pid' => 'fcatalog136',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog178' => 
  array (
    'fcaid' => 'fcatalog178',
    'title' => '图库频道',
    'pid' => '',
    'vieworder' => 91,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '0',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog179' => 
  array (
    'fcaid' => 'fcatalog179',
    'title' => '图库导航下广告位',
    'pid' => 'fcatalog178',
    'vieworder' => 0,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '1',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog172' => 
  array (
    'fcaid' => 'fcatalog172',
    'title' => '手机版界面',
    'pid' => '',
    'vieworder' => 100,
    'chid' => '2',
    'autocheck' => '0',
    'apmid' => '0',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '1',
    'farea' => '0',
  ),
  'fcatalog173' => 
  array (
    'fcaid' => 'fcatalog173',
    'title' => '手机客户端',
    'pid' => 'fcatalog172',
    'vieworder' => 0,
    'chid' => '35',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog174' => 
  array (
    'fcaid' => 'fcatalog174',
    'title' => '手机版',
    'pid' => 'fcatalog172',
    'vieworder' => 0,
    'chid' => '36',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog177' => 
  array (
    'fcaid' => 'fcatalog177',
    'title' => '手机下载图标',
    'pid' => 'fcatalog172',
    'vieworder' => 0,
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'fcatalog28' => 
  array (
    'fcaid' => 'fcatalog28',
    'title' => '辅助信息',
    'pid' => '',
    'vieworder' => 110,
    'chid' => '1',
    'autocheck' => '0',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
    'farea' => '0',
  ),
  'fcatalog168' => 
  array (
    'fcaid' => 'fcatalog168',
    'title' => '帮助中心-广告联系',
    'pid' => 'fcatalog28',
    'vieworder' => 0,
    'chid' => '34',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
  ),
  'fcatalog26' => 
  array (
    'fcaid' => 'fcatalog26',
    'title' => '网站信息',
    'pid' => 'fcatalog28',
    'vieworder' => 0,
    'chid' => '4',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
  ),
  'fcatalog29' => 
  array (
    'fcaid' => 'fcatalog29',
    'title' => '帮助信息',
    'pid' => 'fcatalog28',
    'vieworder' => 0,
    'chid' => '5',
    'autocheck' => '1',
    'apmid' => '22',
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'params' => '',
    'checked' => '0',
  ),
  'phonead' => 
  array (
    'fcaid' => 'phonead',
    'title' => '手机版',
    'pid' => '',
    'vieworder' => 111,
    'chid' => '2',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'toutiao' => 
  array (
    'fcaid' => 'toutiao',
    'title' => '资讯头条上*_90',
    'pid' => 'phonead',
    'vieworder' => 0,
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '*表示宽不限_90表示高90px',
    'ftype' => '0',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'xinfang' => 
  array (
    'fcaid' => 'xinfang',
    'title' => '新房上*_90',
    'pid' => 'phonead',
    'vieworder' => 0,
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'esfang' => 
  array (
    'fcaid' => 'esfang',
    'title' => '二手房上*_90',
    'pid' => 'phonead',
    'vieworder' => 1,
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
  'zufang' => 
  array (
    'fcaid' => 'zufang',
    'title' => '租房上*_90',
    'pid' => 'phonead',
    'vieworder' => 2,
    'chid' => '3',
    'autocheck' => '1',
    'apmid' => 22,
    'nodurat' => '0',
    'customurl' => '',
    'content' => '',
    'ftype' => '0',
    'farea' => '0',
    'params' => '',
    'checked' => '1',
  ),
) ;