<?php
defined('M_COM') || exit('No Permission');
$pafieldspush_kfttj = array (
  'subject' => 
  array (
    'ename' => 'subject',
    'datatype' => 'text',
    'type' => 'pa',
    'tpid' => 'push_kfttj',
    'cname' => '标题',
    'issystem' => '1',
    'iscustom' => '0',
    'iscommon' => '1',
    'issearch' => '0',
    'available' => '1',
    'tbl' => 'push_kfttj',
    'length' => '100',
    'vieworder' => 0,
    'rpid' => '0',
    'wmid' => '0',
    'guide' => '',
    'vdefault' => '',
    'innertext' => '',
    'fromcode' => '0',
    'nohtml' => '1',
    'notnull' => '1',
    'mlimit' => '',
    'regular' => '',
    'min' => '',
    'max' => '',
    'mode' => '1',
    'coid' => '0',
    'cnmode' => '0',
    'cfgs' => '',
    'cfgs0' => '',
    'filter' => '0',
    'editor_height' => '0',
  ),
) ;