# <?exit();?>
# 08cms InstallPack BasicData Dump
# Version: 08cms House 7.1
# Date: 2016-09-07
# --------------------------------------------------------
# Home: www.08cms.com
# --------------------------------------------------------


INSERT INTO #__abrels (arid,cname,remark,source,target,tbl,available,cfgs,cfgs0,content,vieworder) VALUES ('1','楼盘内资讯,问答,特价,周边,沙盘','资讯,问答,特价,周边,沙盘->楼盘','0','0','aalbums','1','array (\n  \'schids\' => \n  array (\n    0 => 1,\n    1 => 106,\n    2 => 107,\n    3 => 8,\n    4 => 111,\n  ),\n  \'tchids\' => \n  array (\n    0 => 4,\n    1 => 115,\n    2 => 116,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 1,\r\n    1 => 106,\r\n    2 => 107,\r\n    3 => 8,\r\n    4 => 111,\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    0 => 4,\r\n    1 => 115,\r\n    2 => 116,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','','0'),
('2','新房团购内户型','户型->新房团购','0','0','aalbums','1','array (\n  \'schids\' => \n  array (\n    0 => 11,\n  ),\n  \'tchids\' => \n  array (\n    0 => 5,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    11\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n  5\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','','0'),
('3','楼盘内(租房,二手,团购,相册,户型)','单个文档(二手房,出租,团购,相册,户型)->单个楼盘','0','0','','1','array (\n  \'schids\' => \n  array (\n    0 => 2,\n    1 => 3,\n    2 => 5,\n    3 => 7,\n    4 => 11,\n  ),\n  \'tchids\' => \n  array (\n    0 => 4,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 2,\r\n    1 => 3,\r\n    2 => 5,\r\n    3 => 7,\r\n    4 => 11,\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    0 => 4,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','在二手里用pid3判断','0'),
('4','公司内经纪人','经纪人->经纪公司','1','1','','1','','','经纪人会员独立注册，注册时选择公司或注册后加入公司。\r\n公司审核加入的经纪人，也可以取消申请，公司允许修改内部经纪人的密码或解审会员。\r\n可以为经济人分配运作资金。可以查看经纪人的基本信息及房源统计信息。','0'),
('5','视频内楼盘','楼盘->视频','0','0','','1','array (\n  \'schids\' => \n  array (\n    0 => 4,\n    1 => 115,\n    2 => 116,\n  ),\n  \'tchids\' => \n  array (\n    0 => 12,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 4,\r\n    1 => 115,\r\n    2 => 116,\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    0 => 12,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','一个视频属于多个楼盘，一个楼盘里面只能加载一个视频','0'),
('6','开发商内楼盘','楼盘->开发商','0','0','','1','array (\n  \'schids\' => \n  array (\n    0 => 4,\n    1 => 115,\n    2 => 116,\n  ),\n  \'tchids\' => \n  array (\n    0 => 13,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 4,\r\n    1 => 115,\r\n    2 => 116,\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    0 => 13,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','一个开发商可以属于多个楼盘，一个楼盘只能有一个开发商','0'),
('12','关联专题','资讯、楼盘、活动、视频、开发商->专题','0','0','aalbum_zt','1','array (\n  \'schids\' => \n  array (\n    0 => 1,\n    1 => 4,\n    2 => 5,\n    3 => 12,\n    4 => 13,\n  ),\n  \'tchids\' => \n  array (\n    0 => 14,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 1,\r\n    1 => 4,\r\n    2 => 5,\r\n    3 => 12,\r\n    4 => 13\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    0 => 14,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','','0'),
('31','设计师案例','设计师->装修案例','0','0','','1','array (\n  \'schids\' => \n  array (\n    0 => 102,\n  ),\n  \'tchids\' => \n  array (\n    0 => 101,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 102,\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    0 => 101,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','','0'),
('32','看房团内楼盘','看房活动下的楼盘','0','0','aalbum_kfhdlp','1','array (\n  \'schids\' => \n  array (\n    0 => 4,\n  ),\n  \'tchids\' => \n  array (\n    0 => 110,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 4,\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    0 => 110,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','','0'),
('33','楼盘内楼盘分销','楼盘分销->楼盘','0','0','','1','array (\n  \'schids\' => \n  array (\n    0 => 113,\n  ),\n  \'tchids\' => \n  array (\n    0 => 4,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 113,\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    0 => 4,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','','0'),
('34','直播内资讯,楼盘,视频','直播->资讯,楼盘,视频','0','0','aalbums_live','1','array (\n  \'schids\' => \n  array (\n    0 => 1,\n    1 => 4,\n    2 => 12,\n  ),\n  \'tchids\' => \n  array (\n    0 => 114,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 1,\r\n    1 => 4,\r\n    2 => 12,\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    0 => 114,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','','0'),
('35','楼盘内的资讯,周边,楼栋(商业地产)','资讯,周边,楼栋->楼盘(含写字楼,商铺,楼栋)','0','0','aalbums_arcs','1','array (\n  \'schids\' => \n  array (\n    0 => 1,\n    1 => 8,\n    2 => 111,\n  ),\n  \'tchids\' => \n  array (\n    1 => 115,\n    2 => 116,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 1,\r\n    1 => 8,\r\n    2 => 111,\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    1 => 115,\r\n    2 => 116,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','','0'),
('36','楼盘内(租房,二手,相册)(商业地产)','单个文档(二手房,出租,相册)->单个楼盘(含写字楼,商铺)','0','0','','1','array (\n  \'schids\' => \n  array (\n    0 => 7,\n    1 => 117,\n    2 => 118,\n    3 => 119,\n    4 => 120,\n  ),\n  \'tchids\' => \n  array (\n    1 => 115,\n    2 => 116,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 7,\r\n    1 => 117,\r\n    2 => 118,\r\n    3 => 119,\r\n    4 => 120,\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    1 => 115,\r\n    2 => 116,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','','0'),
('37','楼栋内户型','户型->楼栋','0','0','aalbums_loudong','1','array (\n  \'schids\' => \n  array (\n    0 => 11,\n  ),\n  \'tchids\' => \n  array (\n    0 => 111,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 11,\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    0 => 111,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','','0'),
('38','房源内图片','房源->图片','0','0','','1','array (\n  \'schids\' => \n  array (\n    0 => 121,\n  ),\n  \'tchids\' => \n  array (\n    0 => 2,\n    1 => 3,\n  ),\n  \'autocheck\' => 1,\n)','array (\r\n  \'schids\' => \r\n  array (\r\n    0 => 121,\r\n  ),\r\n  \'tchids\' => \r\n  array (\r\n    0 => 2,\r\n    1 => 3,\r\n  ),\r\n  \'autocheck\' => 1,\r\n)','(不用于商业地产)','0');
