//语言函数
function lang(str){
	if(!window.langs || !str)return str;
	str = str.split(' ');
	var i, l, ret = '', arg = arguments;
	for(i = 0, l = str.length; i < l; i++)ret += langs[str[i]] ? langs[str[i]] : str[i];
	str = ret.split('%s');
	if(arg.length > 1 && str.length > 1){
		ret = str[0];
		for(i = 1, l = str.length; i < l; i++)ret += (i < arg.length ? arg[i] : '') + str[i];
	}
	ret = ret.replace(/%(\d+)/g, function(a, b){return arg[b] ? arg[b] : a});
	return ret;
}
var langs={
	':':'：',
	'`':'、',
	',':'，',
	'.':'。',
	'!':'！',
	'a':'一个',
	'add':'添加',
	'all':'全部',
	'at':'在',
	'batch':'批量',
	'be':'是',
	'can':'可',
	"can't":'不能',
	'err':'有误',
	'error':'错误',
	'the':'本',
	'this':'此',
	'less':'少于',
	'ge':'个',
	'use':'用',
	'success':'成功',
	'description':'描述',
	'chooseto':'加入选择',
	'new':'新',
	'window':'窗口',
	'open':'打开',
	'page':'页',
	'please':'请',
	'wait':'等待',
	'loading':'载入',
	'endand':'后再',
	'not':'不',
	'support':'支持',
	'upload':'上传',
	'type':'类型',
	'extension':'扩展名',
	'of':'的',
	'or':'或',
	'adjunct':'附件',
	'max':'最大',
	'local':'本地',
	'invalid':'无效的',
	'picture':'图片',
	'file':'文件',
	'preview':'预览',
	'close':'关闭',
	'delete':'删除',
	'modify':'修改',
	'refresh':'刷新',
	'float':'浮动',
	'line':'行',
	'count':'数量',
	'beyond':'超出',
	'purview':'权限',
	'lack':'不足',
	'validate':'有效',
	'scope':'范围',
	'empty':'为空',
	'input':'输入',
	'fall':'不符合',
	'reason':'合法',
	'rule':'规则',
	'length':'长度',
	'data':'数据',
	'date':'日期',
	'integer':'整数',
	'number':'数字',
	'letter':'字母',
	'character':'字符',
	'string':'串',
	'initially':'开始的',
	'format':'格式',
	'email':'电子邮箱',
	'address':'地址',
	'unknow':'未知',
	'detect':'检测',
	'login':'登陆',
	'nologin':'未登陆',
	'default':'默认',
	'player':'播放器',
	'allow':'允许',
	'without':'没有',
	'with':'包括',
	'include':'包含',
	'reach':'已达到',
	'zip':'压缩包',
	'try':'试',
	'process':'正在进行',
	'save':'保存',
	'space':'空间',
	'size':'大小',
	'timeout':'超时',
	'server':'服务器',
	'read':'读',
	'contact':'联系',
	'manager':'管理员',
	'limit':'限制',
	'fixed':'确定',
	'cancel':'取消',
	'letup':'中止',
	'do':'做',
	'other':'其它',
	'operate':'操作',
	'not_empty':'不能为空',
	'wait_err_load':'页面尚未加载完成，请稍候操作！',
	'empty_info':'为必选/填项目',
	'load_item':'载入中...',
	'loading':'加载中...',
	'urllink':'常用链接',
	'fixlink':'固定链接',
	'check_field':'请检查所有必填项目是否完整！',
	'code_e1':'验证码为四位数字！',
	'uname_low':'用户名少于3个字节！',
	'uname_hgh':'用户名超过15个字节！',
	'uname_err':'用户名应为3-15个字节！',
	'pwd_e1':'密码空或包含非法字符（不能用全0作密码）！',
	'pwd_e2':'两次输入的密码不一致！',
	'email_err':'Email 地址无效！',
	'init_field_err':'没有找到数据源，初始化失败！',
	'win_field_err':'关联窗口可能已经刷新或关闭，操作失败！',
	'choose':'请选择...',
	'choose_again':'您选中的项目还需要下一级，请继续选择...',
	'wait_choose':'等候选择...',
	'wait_load_link':'正在载入可发布链接地址，请稍候...',
	'mb_choose':'必需选择 ',
	'can_choose':'还可以选择 ',
	'choosed':'选择了 ',
	'nin':'您',
	'hai':'还',
	'click_add':'请点击下栏中的链接发表新文档。',
	'no_use_item':'没有可用项目',
	'out_num_limit':'超出数量限制，最多选择 %s 条',
	'confirm_del_goods':'确定要删除此商品？',
	'confirm_operate':'确定要继续当前操作？',
	'set_goods_num_err':'数量设置错误，已自动设置为 %s',
	'length_fall_be':'长度不合法，必需为 %1 个字节！',
	'length_fall_between':'长度不合法，必需在 %s - %s 字节之间！',
	'out_and_validate':'超出有效范围 %s - %s ！',
	'inputsubject':'请输入标题内容！',
	'subjectexist':'输入的标题已存在！',
	'subjectavailable':'标题没有重复!',
	'regularerr':'正则检查字串有误，请联系管理员',
	'ajaxxmlerr':'Ajax请求XML文档格式错误，请联系管理员',
	'folder_exist':'文件夹已经存在',
	'invalid_folder_name':'无效的文件夹名称',
	'cant_create_folder':'您没有权限创建文件夹',
	'unknown_err_create_folder':'未知的创建文件夹错误',
	'request_errno':'错误的请求，错误代码：%s',
	'guest_info':'<span style="color:red"><b>%s</b> 您好！登陆后解除部分功能限制</span><br />',
	'map_tip':'按 “ ESC ” 键展开 / 关闭此菜单',
	'gather_progress':'采集正在进行中。。。<br />共请求了 {$pagecount} 个页面<br />并获得了 {$linkcount} 个链接<br />采集到了 {$content} 条内容<br />入库完成 {$output} 条记录<br />持续时间 {$usetime}',
	'hours':'小时',
	'minutes':'分钟',
	'seconds':'秒',
	'break_progress':'要中止操作请点这里<<',
	'result_exists':'选择的项目已存在',
	'no_msg_gate':'系统没有设置短信接口平台!',
	'mobile_format_fail':'手机号码格式错误',
	'repeat_mobile_not_modify':'已认证过的手机号码，无需重复认证，请留空',
	'donot_repeat_operate':'请不要重复提交，等待系统响应',
	'msgcode_send_ok':'确认码已发送到您手机，请注意查收。[%s]后可重发',
	'msgcode_send_err':'发送信息失败，请联系管理员！',
	'memcert_checking':'您已有认证在申请中，请先删除之前的认证申请',
	'input_string':'请输入要测试的字符串',
	'string_notmodify':'无修改动作',
	'string_available':'测试的字符串可以正常用',
	'string_exists':'测试的字符串已存在，请重新输入',
	'copy_ok':'复制成功！',
	'confirm_delete':'确定要删除选定的项目吗？',
	'vote_max_count':'最多只能添加 %s 个投票。',
	'vote_max_items':'已达到最大投票选项个数。',
	'vote_info_miss':'投票标题和说明必填，投票选项大于等于两个！',
	'vote_confirm_delete':'确定要删除第 %s 个选项么？',
	'not_find_form':'没有找到 Form 表单！',
	'btn_search':' 搜 索 ',
	'not_find_place':'没有找到您查找的地方',
	'confirm_marker':'确定标记在这个位置吗？',
	'max_items_limit':'已达到最大项数限制。',
	'texts_item_between':'第 %s 行第 %s 列长度需在 %s 到 %s 个字节之间',
	'texts_item_least':'第 %s 行第 %s 列长度需大于 %s 个字节',
	'texts_item_limit':'第 %s 行第 %s 列长度需在 %s 个字节以内',
	'texts_items_between':'项数应在 %s 到 %s 项之间',
	'texts_items_least':'项数应大于 %s 项',
	'texts_items_limit':'项数应小于 %s 项',
	'comp_empty':'请输入要比较的内容',
	'comp_differ':'比较的内容不一致！'
}
